//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace AppEscritorio.wsDespacho {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://webService/", ConfigurationName="wsDespacho.wsSeguimiento")]
    public interface wsSeguimiento {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://webService/wsSeguimiento/agregarDespachoRequest", ReplyAction="http://webService/wsSeguimiento/agregarDespachoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        AppEscritorio.wsDespacho.agregarDespachoResponse agregarDespacho(AppEscritorio.wsDespacho.agregarDespachoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webService/wsSeguimiento/agregarDespachoRequest", ReplyAction="http://webService/wsSeguimiento/agregarDespachoResponse")]
        System.Threading.Tasks.Task<AppEscritorio.wsDespacho.agregarDespachoResponse> agregarDespachoAsync(AppEscritorio.wsDespacho.agregarDespachoRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://webService/wsSeguimiento/NuevoEstadoRequest", ReplyAction="http://webService/wsSeguimiento/NuevoEstadoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        AppEscritorio.wsDespacho.NuevoEstadoResponse NuevoEstado(AppEscritorio.wsDespacho.NuevoEstadoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webService/wsSeguimiento/NuevoEstadoRequest", ReplyAction="http://webService/wsSeguimiento/NuevoEstadoResponse")]
        System.Threading.Tasks.Task<AppEscritorio.wsDespacho.NuevoEstadoResponse> NuevoEstadoAsync(AppEscritorio.wsDespacho.NuevoEstadoRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://webService/wsSeguimiento/listarDespachosRequest", ReplyAction="http://webService/wsSeguimiento/listarDespachosResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        AppEscritorio.wsDespacho.listarDespachosResponse listarDespachos(AppEscritorio.wsDespacho.listarDespachosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webService/wsSeguimiento/listarDespachosRequest", ReplyAction="http://webService/wsSeguimiento/listarDespachosResponse")]
        System.Threading.Tasks.Task<AppEscritorio.wsDespacho.listarDespachosResponse> listarDespachosAsync(AppEscritorio.wsDespacho.listarDespachosRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://webService/wsSeguimiento/modEstadoDespachoRequest", ReplyAction="http://webService/wsSeguimiento/modEstadoDespachoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        AppEscritorio.wsDespacho.modEstadoDespachoResponse modEstadoDespacho(AppEscritorio.wsDespacho.modEstadoDespachoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webService/wsSeguimiento/modEstadoDespachoRequest", ReplyAction="http://webService/wsSeguimiento/modEstadoDespachoResponse")]
        System.Threading.Tasks.Task<AppEscritorio.wsDespacho.modEstadoDespachoResponse> modEstadoDespachoAsync(AppEscritorio.wsDespacho.modEstadoDespachoRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webService/")]
    public partial class despacho : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int comuna_id_comunaField;
        
        private string direccionField;
        
        private int envio_id_envioField;
        
        private int estado_id_estadoField;
        
        private int id_despachoField;
        
        private int telefonoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int comuna_id_comuna {
            get {
                return this.comuna_id_comunaField;
            }
            set {
                this.comuna_id_comunaField = value;
                this.RaisePropertyChanged("comuna_id_comuna");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string direccion {
            get {
                return this.direccionField;
            }
            set {
                this.direccionField = value;
                this.RaisePropertyChanged("direccion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int envio_id_envio {
            get {
                return this.envio_id_envioField;
            }
            set {
                this.envio_id_envioField = value;
                this.RaisePropertyChanged("envio_id_envio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int estado_id_estado {
            get {
                return this.estado_id_estadoField;
            }
            set {
                this.estado_id_estadoField = value;
                this.RaisePropertyChanged("estado_id_estado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int id_despacho {
            get {
                return this.id_despachoField;
            }
            set {
                this.id_despachoField = value;
                this.RaisePropertyChanged("id_despacho");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public int telefono {
            get {
                return this.telefonoField;
            }
            set {
                this.telefonoField = value;
                this.RaisePropertyChanged("telefono");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="agregarDespacho", WrapperNamespace="http://webService/", IsWrapped=true)]
    public partial class agregarDespachoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webService/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public AppEscritorio.wsDespacho.despacho arg0;
        
        public agregarDespachoRequest() {
        }
        
        public agregarDespachoRequest(AppEscritorio.wsDespacho.despacho arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="agregarDespachoResponse", WrapperNamespace="http://webService/", IsWrapped=true)]
    public partial class agregarDespachoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webService/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public agregarDespachoResponse() {
        }
        
        public agregarDespachoResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="NuevoEstado", WrapperNamespace="http://webService/", IsWrapped=true)]
    public partial class NuevoEstadoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webService/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int p_id_despacho;
        
        public NuevoEstadoRequest() {
        }
        
        public NuevoEstadoRequest(int p_id_despacho) {
            this.p_id_despacho = p_id_despacho;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="NuevoEstadoResponse", WrapperNamespace="http://webService/", IsWrapped=true)]
    public partial class NuevoEstadoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webService/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public NuevoEstadoResponse() {
        }
        
        public NuevoEstadoResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarDespachos", WrapperNamespace="http://webService/", IsWrapped=true)]
    public partial class listarDespachosRequest {
        
        public listarDespachosRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarDespachosResponse", WrapperNamespace="http://webService/", IsWrapped=true)]
    public partial class listarDespachosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webService/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public AppEscritorio.wsDespacho.despacho[] @return;
        
        public listarDespachosResponse() {
        }
        
        public listarDespachosResponse(AppEscritorio.wsDespacho.despacho[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modEstadoDespacho", WrapperNamespace="http://webService/", IsWrapped=true)]
    public partial class modEstadoDespachoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webService/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int p_id_despacho;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webService/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int p_estado_id_estado;
        
        public modEstadoDespachoRequest() {
        }
        
        public modEstadoDespachoRequest(int p_id_despacho, int p_estado_id_estado) {
            this.p_id_despacho = p_id_despacho;
            this.p_estado_id_estado = p_estado_id_estado;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modEstadoDespachoResponse", WrapperNamespace="http://webService/", IsWrapped=true)]
    public partial class modEstadoDespachoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webService/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public modEstadoDespachoResponse() {
        }
        
        public modEstadoDespachoResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface wsSeguimientoChannel : AppEscritorio.wsDespacho.wsSeguimiento, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class wsSeguimientoClient : System.ServiceModel.ClientBase<AppEscritorio.wsDespacho.wsSeguimiento>, AppEscritorio.wsDespacho.wsSeguimiento {
        
        public wsSeguimientoClient() {
        }
        
        public wsSeguimientoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public wsSeguimientoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsSeguimientoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsSeguimientoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AppEscritorio.wsDespacho.agregarDespachoResponse AppEscritorio.wsDespacho.wsSeguimiento.agregarDespacho(AppEscritorio.wsDespacho.agregarDespachoRequest request) {
            return base.Channel.agregarDespacho(request);
        }
        
        public bool agregarDespacho(AppEscritorio.wsDespacho.despacho arg0) {
            AppEscritorio.wsDespacho.agregarDespachoRequest inValue = new AppEscritorio.wsDespacho.agregarDespachoRequest();
            inValue.arg0 = arg0;
            AppEscritorio.wsDespacho.agregarDespachoResponse retVal = ((AppEscritorio.wsDespacho.wsSeguimiento)(this)).agregarDespacho(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AppEscritorio.wsDespacho.agregarDespachoResponse> AppEscritorio.wsDespacho.wsSeguimiento.agregarDespachoAsync(AppEscritorio.wsDespacho.agregarDespachoRequest request) {
            return base.Channel.agregarDespachoAsync(request);
        }
        
        public System.Threading.Tasks.Task<AppEscritorio.wsDespacho.agregarDespachoResponse> agregarDespachoAsync(AppEscritorio.wsDespacho.despacho arg0) {
            AppEscritorio.wsDespacho.agregarDespachoRequest inValue = new AppEscritorio.wsDespacho.agregarDespachoRequest();
            inValue.arg0 = arg0;
            return ((AppEscritorio.wsDespacho.wsSeguimiento)(this)).agregarDespachoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AppEscritorio.wsDespacho.NuevoEstadoResponse AppEscritorio.wsDespacho.wsSeguimiento.NuevoEstado(AppEscritorio.wsDespacho.NuevoEstadoRequest request) {
            return base.Channel.NuevoEstado(request);
        }
        
        public int NuevoEstado(int p_id_despacho) {
            AppEscritorio.wsDespacho.NuevoEstadoRequest inValue = new AppEscritorio.wsDespacho.NuevoEstadoRequest();
            inValue.p_id_despacho = p_id_despacho;
            AppEscritorio.wsDespacho.NuevoEstadoResponse retVal = ((AppEscritorio.wsDespacho.wsSeguimiento)(this)).NuevoEstado(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AppEscritorio.wsDespacho.NuevoEstadoResponse> AppEscritorio.wsDespacho.wsSeguimiento.NuevoEstadoAsync(AppEscritorio.wsDespacho.NuevoEstadoRequest request) {
            return base.Channel.NuevoEstadoAsync(request);
        }
        
        public System.Threading.Tasks.Task<AppEscritorio.wsDespacho.NuevoEstadoResponse> NuevoEstadoAsync(int p_id_despacho) {
            AppEscritorio.wsDespacho.NuevoEstadoRequest inValue = new AppEscritorio.wsDespacho.NuevoEstadoRequest();
            inValue.p_id_despacho = p_id_despacho;
            return ((AppEscritorio.wsDespacho.wsSeguimiento)(this)).NuevoEstadoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AppEscritorio.wsDespacho.listarDespachosResponse AppEscritorio.wsDespacho.wsSeguimiento.listarDespachos(AppEscritorio.wsDespacho.listarDespachosRequest request) {
            return base.Channel.listarDespachos(request);
        }
        
        public AppEscritorio.wsDespacho.despacho[] listarDespachos() {
            AppEscritorio.wsDespacho.listarDespachosRequest inValue = new AppEscritorio.wsDespacho.listarDespachosRequest();
            AppEscritorio.wsDespacho.listarDespachosResponse retVal = ((AppEscritorio.wsDespacho.wsSeguimiento)(this)).listarDespachos(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AppEscritorio.wsDespacho.listarDespachosResponse> AppEscritorio.wsDespacho.wsSeguimiento.listarDespachosAsync(AppEscritorio.wsDespacho.listarDespachosRequest request) {
            return base.Channel.listarDespachosAsync(request);
        }
        
        public System.Threading.Tasks.Task<AppEscritorio.wsDespacho.listarDespachosResponse> listarDespachosAsync() {
            AppEscritorio.wsDespacho.listarDespachosRequest inValue = new AppEscritorio.wsDespacho.listarDespachosRequest();
            return ((AppEscritorio.wsDespacho.wsSeguimiento)(this)).listarDespachosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AppEscritorio.wsDespacho.modEstadoDespachoResponse AppEscritorio.wsDespacho.wsSeguimiento.modEstadoDespacho(AppEscritorio.wsDespacho.modEstadoDespachoRequest request) {
            return base.Channel.modEstadoDespacho(request);
        }
        
        public bool modEstadoDespacho(int p_id_despacho, int p_estado_id_estado) {
            AppEscritorio.wsDespacho.modEstadoDespachoRequest inValue = new AppEscritorio.wsDespacho.modEstadoDespachoRequest();
            inValue.p_id_despacho = p_id_despacho;
            inValue.p_estado_id_estado = p_estado_id_estado;
            AppEscritorio.wsDespacho.modEstadoDespachoResponse retVal = ((AppEscritorio.wsDespacho.wsSeguimiento)(this)).modEstadoDespacho(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AppEscritorio.wsDespacho.modEstadoDespachoResponse> AppEscritorio.wsDespacho.wsSeguimiento.modEstadoDespachoAsync(AppEscritorio.wsDespacho.modEstadoDespachoRequest request) {
            return base.Channel.modEstadoDespachoAsync(request);
        }
        
        public System.Threading.Tasks.Task<AppEscritorio.wsDespacho.modEstadoDespachoResponse> modEstadoDespachoAsync(int p_id_despacho, int p_estado_id_estado) {
            AppEscritorio.wsDespacho.modEstadoDespachoRequest inValue = new AppEscritorio.wsDespacho.modEstadoDespachoRequest();
            inValue.p_id_despacho = p_id_despacho;
            inValue.p_estado_id_estado = p_estado_id_estado;
            return ((AppEscritorio.wsDespacho.wsSeguimiento)(this)).modEstadoDespachoAsync(inValue);
        }

        internal object agregarDespachoAsync()
        {
            throw new NotImplementedException();
        }
    }
}
