//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppEscritorio.wsAlphilia {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://webService/", ConfigurationName="wsAlphilia.wsAlphilia")]
    public interface wsAlphilia {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://webService/wsAlphilia/ListaAlphiliaInRequest", ReplyAction="http://webService/wsAlphilia/ListaAlphiliaInResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        AppEscritorio.wsAlphilia.ListaAlphiliaInResponse ListaAlphiliaIn(AppEscritorio.wsAlphilia.ListaAlphiliaInRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webService/wsAlphilia/ListaAlphiliaInRequest", ReplyAction="http://webService/wsAlphilia/ListaAlphiliaInResponse")]
        System.Threading.Tasks.Task<AppEscritorio.wsAlphilia.ListaAlphiliaInResponse> ListaAlphiliaInAsync(AppEscritorio.wsAlphilia.ListaAlphiliaInRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://webService/wsAlphilia/ListaAlphiliaLiRequest", ReplyAction="http://webService/wsAlphilia/ListaAlphiliaLiResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        AppEscritorio.wsAlphilia.ListaAlphiliaLiResponse ListaAlphiliaLi(AppEscritorio.wsAlphilia.ListaAlphiliaLiRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webService/wsAlphilia/ListaAlphiliaLiRequest", ReplyAction="http://webService/wsAlphilia/ListaAlphiliaLiResponse")]
        System.Threading.Tasks.Task<AppEscritorio.wsAlphilia.ListaAlphiliaLiResponse> ListaAlphiliaLiAsync(AppEscritorio.wsAlphilia.ListaAlphiliaLiRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webService/")]
    public partial class insumo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int id_insumoField;
        
        private string imgField;
        
        private string nombreField;
        
        private int stockField;
        
        private int valorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int id_insumo {
            get {
                return this.id_insumoField;
            }
            set {
                this.id_insumoField = value;
                this.RaisePropertyChanged("id_insumo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string img {
            get {
                return this.imgField;
            }
            set {
                this.imgField = value;
                this.RaisePropertyChanged("img");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int stock {
            get {
                return this.stockField;
            }
            set {
                this.stockField = value;
                this.RaisePropertyChanged("stock");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int valor {
            get {
                return this.valorField;
            }
            set {
                this.valorField = value;
                this.RaisePropertyChanged("valor");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webService/")]
    public partial class libro : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int anio_edicionField;
        
        private string autorField;
        
        private int id_libroField;
        
        private string imgField;
        
        private int isbnField;
        
        private int paginasField;
        
        private string reseniaField;
        
        private int stockField;
        
        private string tituloField;
        
        private int valorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int anio_edicion {
            get {
                return this.anio_edicionField;
            }
            set {
                this.anio_edicionField = value;
                this.RaisePropertyChanged("anio_edicion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string autor {
            get {
                return this.autorField;
            }
            set {
                this.autorField = value;
                this.RaisePropertyChanged("autor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int id_libro {
            get {
                return this.id_libroField;
            }
            set {
                this.id_libroField = value;
                this.RaisePropertyChanged("id_libro");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string img {
            get {
                return this.imgField;
            }
            set {
                this.imgField = value;
                this.RaisePropertyChanged("img");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int isbn {
            get {
                return this.isbnField;
            }
            set {
                this.isbnField = value;
                this.RaisePropertyChanged("isbn");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public int paginas {
            get {
                return this.paginasField;
            }
            set {
                this.paginasField = value;
                this.RaisePropertyChanged("paginas");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string resenia {
            get {
                return this.reseniaField;
            }
            set {
                this.reseniaField = value;
                this.RaisePropertyChanged("resenia");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public int stock {
            get {
                return this.stockField;
            }
            set {
                this.stockField = value;
                this.RaisePropertyChanged("stock");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string titulo {
            get {
                return this.tituloField;
            }
            set {
                this.tituloField = value;
                this.RaisePropertyChanged("titulo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public int valor {
            get {
                return this.valorField;
            }
            set {
                this.valorField = value;
                this.RaisePropertyChanged("valor");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ListaAlphiliaIn", WrapperNamespace="http://webService/", IsWrapped=true)]
    public partial class ListaAlphiliaInRequest {
        
        public ListaAlphiliaInRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ListaAlphiliaInResponse", WrapperNamespace="http://webService/", IsWrapped=true)]
    public partial class ListaAlphiliaInResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webService/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public AppEscritorio.wsAlphilia.insumo[] @return;
        
        public ListaAlphiliaInResponse() {
        }
        
        public ListaAlphiliaInResponse(AppEscritorio.wsAlphilia.insumo[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ListaAlphiliaLi", WrapperNamespace="http://webService/", IsWrapped=true)]
    public partial class ListaAlphiliaLiRequest {
        
        public ListaAlphiliaLiRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ListaAlphiliaLiResponse", WrapperNamespace="http://webService/", IsWrapped=true)]
    public partial class ListaAlphiliaLiResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webService/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public AppEscritorio.wsAlphilia.libro[] @return;
        
        public ListaAlphiliaLiResponse() {
        }
        
        public ListaAlphiliaLiResponse(AppEscritorio.wsAlphilia.libro[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface wsAlphiliaChannel : AppEscritorio.wsAlphilia.wsAlphilia, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class wsAlphiliaClient : System.ServiceModel.ClientBase<AppEscritorio.wsAlphilia.wsAlphilia>, AppEscritorio.wsAlphilia.wsAlphilia {
        
        public wsAlphiliaClient() {
        }
        
        public wsAlphiliaClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public wsAlphiliaClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsAlphiliaClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsAlphiliaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AppEscritorio.wsAlphilia.ListaAlphiliaInResponse AppEscritorio.wsAlphilia.wsAlphilia.ListaAlphiliaIn(AppEscritorio.wsAlphilia.ListaAlphiliaInRequest request) {
            return base.Channel.ListaAlphiliaIn(request);
        }
        
        public AppEscritorio.wsAlphilia.insumo[] ListaAlphiliaIn() {
            AppEscritorio.wsAlphilia.ListaAlphiliaInRequest inValue = new AppEscritorio.wsAlphilia.ListaAlphiliaInRequest();
            AppEscritorio.wsAlphilia.ListaAlphiliaInResponse retVal = ((AppEscritorio.wsAlphilia.wsAlphilia)(this)).ListaAlphiliaIn(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AppEscritorio.wsAlphilia.ListaAlphiliaInResponse> AppEscritorio.wsAlphilia.wsAlphilia.ListaAlphiliaInAsync(AppEscritorio.wsAlphilia.ListaAlphiliaInRequest request) {
            return base.Channel.ListaAlphiliaInAsync(request);
        }
        
        public System.Threading.Tasks.Task<AppEscritorio.wsAlphilia.ListaAlphiliaInResponse> ListaAlphiliaInAsync() {
            AppEscritorio.wsAlphilia.ListaAlphiliaInRequest inValue = new AppEscritorio.wsAlphilia.ListaAlphiliaInRequest();
            return ((AppEscritorio.wsAlphilia.wsAlphilia)(this)).ListaAlphiliaInAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AppEscritorio.wsAlphilia.ListaAlphiliaLiResponse AppEscritorio.wsAlphilia.wsAlphilia.ListaAlphiliaLi(AppEscritorio.wsAlphilia.ListaAlphiliaLiRequest request) {
            return base.Channel.ListaAlphiliaLi(request);
        }
        
        public AppEscritorio.wsAlphilia.libro[] ListaAlphiliaLi() {
            AppEscritorio.wsAlphilia.ListaAlphiliaLiRequest inValue = new AppEscritorio.wsAlphilia.ListaAlphiliaLiRequest();
            AppEscritorio.wsAlphilia.ListaAlphiliaLiResponse retVal = ((AppEscritorio.wsAlphilia.wsAlphilia)(this)).ListaAlphiliaLi(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AppEscritorio.wsAlphilia.ListaAlphiliaLiResponse> AppEscritorio.wsAlphilia.wsAlphilia.ListaAlphiliaLiAsync(AppEscritorio.wsAlphilia.ListaAlphiliaLiRequest request) {
            return base.Channel.ListaAlphiliaLiAsync(request);
        }
        
        public System.Threading.Tasks.Task<AppEscritorio.wsAlphilia.ListaAlphiliaLiResponse> ListaAlphiliaLiAsync() {
            AppEscritorio.wsAlphilia.ListaAlphiliaLiRequest inValue = new AppEscritorio.wsAlphilia.ListaAlphiliaLiRequest();
            return ((AppEscritorio.wsAlphilia.wsAlphilia)(this)).ListaAlphiliaLiAsync(inValue);
        }
    }
}
